### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by meetgyn** [Aravindha1234u/SocialScraper#2]
I've tried everything and I can't install it.
I'm using Debian 10

jsonlib  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Aravindha1234u** [comment]
Update your gcc compiler if it exist and if it does not exist then install
it

**Comment by meetgyn** [comment]
Thanks man. I did installation, but the error continues.

root @ Lab1: / opt / osint / SocialScraper # ** apt-get install build-essential python-dev **
Reading package lists ... Done
Building dependency tree
Reading status information ... Ready
** build-essential is already the newest version (12.6).
python-dev is already the newest version (2.7.16-1). **

root @ Lab1: / opt / osint / SocialScraper # ** apt-get install gcc-8 **
Reading package lists ... Done
Building dependency tree
Reading status information ... Ready
** gcc-8 is already the newest version (8.3.0-6). **
0 updated packages, 0 new packages installed, 0 to be removed and 17 not updated.
root @ Lab1: / opt / osint / SocialScraper # ** apt-get install python3.7-dev **
Reading package lists ... Done
Building dependency tree
Reading status information ... Ready
** python3.7-dev is already the newest version (3.7.3-2 + deb10u1).
python3.7-dev configured to install manually. **

root @ Lab1: / opt / osint / SocialScraper # ** sudo apt-get install libxml2-dev libxslt1-dev **
Reading package lists ... Done
Building dependency tree
Reading status information ... Ready
The following additional packages will be installed:
  icu-devtools libicu-dev libicu63
Suggested packages:
  icu-doc
The following NEW packages will be installed:
  icu-devtools libicu-dev libxml2-dev libxslt1-dev
The following packages will be updated:
  libicu63
1 updated packages, 4 new packages installed, 0 to be removed and 16 not updated.
You must download 9,894 kB / 19.0 MB of files.
After this operation, an additional 49.5 MB of disk space will be used.
Do you want to continue? [Y / n] Y

**Comment by Aravindha1234u** [comment]
Can you try this
sudo apt-get install libmysqlclient-dev

**Comment by meetgyn** [comment]
Now yes. I managed to do the installation. Thank you very much for your help.
One question, do I need to create Facebook, Twitter and Instagram APIs to put in it?

**Comment by Aravindha1234u** [comment]
**Could say the way so that others can get a solution from this know**

* Use need to get Google API : [google](https://developers.google.com/)
* from imagga get api key and secret key : [imagga](https://imagga.com)
* API key from deepai : [deepai](https://deepai.org)

**Comment by Aravindha1234u** [comment]
Check the New release
